# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Pavatar
version:      1.00
version_from: lib/Net/Pavatar.pm
installdirs:  site
requires:
    GD:                            1.48
    LWPx::ParanoidAgent:           1.03
    Regexp::Common:                2.120
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
