# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Pavatar
version:      0.692
version_from: lib/Net/Pavatar.pm
installdirs:  site
requires:
    GD:                            0
    LWPx::ParanoidAgent:           0
    Regexp::Common:                0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
